name: "ngrok SSH tunnel (Ubuntu 22.04)"

on:
  workflow_dispatch:

jobs:
  ngrok_ssh_tunnel:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: set pass
        run:  mkdir -p /var/run/sshd
      - run: sudo useradd -m saHOST
      - run: sudo adduser saHOST sudo
      - run: echo 'saHOST:127qwe' | sudo chpasswd
      - run: getent passwd | grep /bin/bash
      - run: sudo -i
      - run: whoami
      #- run: sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd
      #- run: echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
      #- run: sudo su
      #- run:  echo "PasswordAuthentication no" >> /etc/ssh/sshd_config
      - name: Start SSH via ngrok
        run: ./start_ngrok_tunnel.sh
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          SSH_PUBLIC_KEY: ${{ secrets.NGROK_SSH_PUBLIC_KEY }}
        shell: bash
      - name: Keep tunnel alive for 24 hours
        run: sleep 86400
        shell: bash
